config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users

  resources :pets, except: [:show]
  resources :sittings, except: [:destroy] do
    collection do
      get :my_sittings
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :info, presence: true
  validates :species, presence: true #add selector????
  mount_uploader :photo, PhotoUploader
end

app/models/sitting.rb
class Sitting < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: :owner_id
  belongs_to :sitter, class_name: "User", foreign_key: :sitter_id, optional: true
  validates :start_date, presence: true
  validates :end_date, presence: true
 # validates :rating, numericality: { only_integer: true }, inclusion: { in: [ 1, 2, 3, 4, 5] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pets, dependent: :destroy
  #owner:
  has_many :sittings_for_me, class_name: "Sitting", foreign_key: :owner_id
  #sitter:
  has_many :sittings_by_me, class_name: "Sitting", foreign_key: :sitter_id
  validates :name, presence: true
  validates :user_name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :phone_number, presence: true
  #check if needed
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:edit, :update, :destroy]
  # before_action :set user
  def index
    @pets = current_user.pets.all
    # @user = current_user
    # @pets = @user.pets.all
  end

  def new
    # @user = current_user
    @pet = Pet.new
  end

  def create
    # @user = current_user
    @pet = Pet.new(pet_params)
    @pet.user = current_user

    if @pet.save
      redirect_to pets_path, notice: 'pet was added'
    else
      # ??????? where to render
      # render to profile page
      render :new#, :locals => { :pet => @pet }
    end
  end

  def edit
    # @pet = current_user.pets.find(params[:id])
  end

  def update
    # @pet = current_user.pets.find(params[:id])
    @pet.update(pet_params)
    redirect_to pets_path
  end

  def destroy
    # @pet = current_user.pets.find(params[:id])
    # @pet = Pet.find(params[:id])
    @pet.destroy
  end

  private
  def set_pet
    @pet = Pet.find(params[:id])
  end
  def pet_params
    params.require(:pet).permit(:name, :species, :info, :photo)
  end
end

app/controllers/sittings_controller.rb
class SittingsController < ApplicationController
  # before_action :set_sitting
  def index
    if params[:query].present?
      @sittings = Sitting.joins(:owner).where("address ILIKE ?", "%#{params[:query].capitalize}%" )
    else
      @sittings = Sitting.all
    end
  end

  def my_sittings
    @sittings = current_user.sittings_by_me
  end


  def show
    set_sitting
    @owner = @sitting.owner
    @pets = @owner.pets
  end

  def new
    @sitting = Sitting.new
  end

  def create
    @sitting = Sitting.create(sitting_params)
    if @sitting.save
      redirect_to @sitting, notice: 'sitting was added'
    else
      render :new
    end
  end

  def update
    set_sitting
    # if current_user.sitter?
      @sitting.sitter = current_user
      @sitting.save
      redirect_to @sitting
    # else
      #render to edit the sitting details as owner
    # end
  end
  private
  def set_sitting
    @sitting = Sitting.find(params[:id])
  end
  def sitting_params
    params.require(:sitting).permit(:owner, :photo, :sitter, :start_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body class=" <%= params[:controller] %> <%= params[:action] %>">
    <%= render 'components/navbar' %>
    <%= render 'components/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%#= render 'components/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'components/banner' %>
<section id="services">
<div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">What we do</h2>
            <h3 class="section-subheading text-muted">Connect pet lovers everywhere.</h3>
          </div>
        </div>
        <div class="row text-center">
          <div class="col-md-4">
            <%= image_tag "iconenew.png", class: "icone" %>
            <h4 class="service-heading">Join</h4>
            <p class="text-muted">Join a thriving community of pet lovers. Experience the joy of pet companionship. Own a pet but retain your freedom</p>
          </div>
          <div class="col-md-4">
            <%= image_tag "iconnew2.png", class: "icone" %>
            <h4 class="service-heading">Connect</h4>
            <p class="text-muted">Connect with and support other like-minded pet lovers</p>
          </div>
          <div class="col-md-4">
            <%= image_tag "relax.png", class: "icone" %>
            <h4 class="service-heading">Relax</h4>
            <p class="text-muted">Relax knowing that your four legged family members are well cared for or share your time withour furry friends.</p>
          </div>
        </div>
      </div>

app/views/pets/create.html.erb
<h1>Pets#create</h1>
<p>Find me in app/views/pets/create.html.erb</p>

app/views/pets/destroy.html.erb
<h1>Pets#destroy</h1>
<p>Find me in app/views/pets/destroy.html.erb</p>

app/views/pets/edit.html.erb
<h1>Pets#edit</h1>
<p>Find me in app/views/pets/edit.html.erb</p>

app/views/pets/index.html.erb
<div class="pets-index-header">
  <h1>All my pets</h1>
</div>

<div class="pets-index">
  <% @pets.each do |pet| %>
    <div class="show-pets"> <!-- ???change-class-name -->
      <div class="pet-image">
         <%#= image_tag pet.photo%>
      </div>
      <div class="pet-info"> <!-- ???change-class-name -->
        <ul>
        <li>name: <%= pet.name %></li>
        <li>species: <%= pet.species %></li>
        <li>info: <%= pet.info %></li>
      </div>
    </div>
  <% end %>
</div>

app/views/pets/new.html.erb
# Not finished as priorities changed

<h1>Add a Pet</h1>
<p>Find me in app/views/pets/new.html.erb</p>

<%= simple_form_for(@pet) do |f| %>
 <%= f.error_notification %>
 <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

 <div class="form-inputs">
   <%= f.input :name %>
   <%= f.input :species %>
   <%= f.input :info %>
 </div>

 <div class="form-actions">
   <%= f.button :submit %>
 </div>
<% end %>

app/views/pets/show.html.erb
<h1>Pets#show</h1>
<p>Find me in app/views/pets/show.html.erb</p>

app/views/pets/update.html.erb
<h1>Pets#update</h1>
<p>Find me in app/views/pets/update.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/sittings/_sitting_form.html.erb
<%= simple_form_for(@sitting) do |f| %>
<% if @sitting.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @sitting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :description %>
    <%= f.submit %>
<% end %>

app/views/sittings/create.html.erb
<h1>Sittings#create</h1>
<p>Find me in app/views/sittings/create.html.erb</p>

app/views/sittings/edit.html.erb
<h1>Sittings#edit</h1>
<p>Find me in app/views/sittings/edit.html.erb</p>

app/views/sittings/index.html.erb
<br><br>
<div class="search text-center", style="margin-top:100px">
  <form class="form-inline my-2 my-lg-0">
    <input class="form-control mr-sm-2" name="query" placeholder="Search" aria-label="Search" value="" type="search">
    <!-- <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button> -->
  </form>
</div>


<%= render 'components/cards' %>

app/views/sittings/my_sittings.html.erb
<div class="my-sittings-header text-center", style="margin-top:100px;">
  <h1>Sitting I applied to</h1>
</div>

<%= render 'components/cards' %>


<%#= render 'cards' %>

app/views/sittings/new.html.erb
<div class="new-header text-center">
    <h1>New sitting</h1>
  </div>
<div class="new-container">
  <div class="new-form">
    <%= render 'sitting_form' %>
  </div>
</div>

app/views/sittings/show.html.erb
<div id="carousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel" data-slide-to="0" class="active"></li>
    <li data-target="#carousel" data-slide-to="1"></li>
    <!-- <li data-target="#carousel" data-slide-to="2"></li> -->
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag "dog1.jpg" %>
      <!-- <img src="/assets/dog1.jpg"> -->
    </div>
    <div class="item">
      <%= image_tag "cat1.jpg" %>
      <!-- <img src="/assets/cat1.jpg"> -->
    </div>

    <div class="item">
      <%= image_tag "rat1.jpg" %>
      <!-- <img src="/assets/rat1.jpg"> -->
    </div>

    <!-- <div class="item"> -->
      <!-- <img src="/assets/rat1.jpg"> -->
    <!-- </div> -->
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="header", style="margin-top: 60px">
  <div class="show-name text-center">
    <h1>Sitting info</h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-8 mx-auto text-center">
      <h2 class="section-heading text-white">Owner</h2>
      <div>
        <img src="/assets/cross_eyed_woman.jpg" class="avatar-large"/>

      </div>
          <ul>
            <li>name: <%= @owner.name %></li>
            <li>user name: <%= @owner.user_name %></li>
            <li>address: <%= @owner.address %></li>
            <li>phone number: <%= @owner.phone_number %></li>
            <li>email: <%= @owner.email %></li>
            <li>description: <%= @owner.description %></li>
          </ul>
    </div>
  </div>
</div>
  <div class="container">
  <div class="row">
    <div class="col-lg-8 mx-auto text-center">
          <h4><strong>Pets</strong></h4>
    <% @pets.each do |pet| %>

          <ul>
          <br>
          <li><em>name: <%= pet.name %></em></li>
          <li>species: <%= pet.species %></li>
          <li>info: <%= pet.info %></li>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
  <div class="sitting-description text-center">
    <div class="specific-sitting-description">
      <% if @sitting.description != nil %>
        <h4>Sitting description</h4>
        <%= @sitting.description %>
      <% end %>
    </div>
    <div class="sitting-date">
      <br>
      <br>
      <h4><strong>Date:</strong></h4>
      <%= @sitting.start_date %> - <%= @sitting.end_date %>
    </div>
  </div>
  <div class="apply-to-sitting">
    <% if @sitting.sitter.nil? %>
    <%= link_to "Apply for sitting", sitting_path(@sitting), method: :patch , class: "btn btn-primary" %>
    <% else %>
      <div class="btn btn-success">
        Applied successfully
      </div>
    <% end %>
      <!-- Apply for sitting -->
  </div>
</div>

app/views/sittings/update.html.erb
<h1>Sittings#update</h1>
<p>Find me in app/views/sittings/update.html.erb</p>